services:
  mongodb:
    image: mongo:latest
    container_name: mongo-dev-microservices
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
      - mongo-config:/data/configdb

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express-microservices
    environment:
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  entry-service:
    build:
      context: ./services/entry-service
      dockerfile: Dockerfile
    container_name: entry-service
    ports:
      - "3001:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongodb:27017/laWiki?authSource=admin

  user-service:
    build:
      context: ./services/user-service
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "3002:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongodb:27017/laWiki?authSource=admin

  version-service:
    build:
      context: ./services/version-service
      dockerfile: Dockerfile
    container_name: version-service
    ports:
      - "3003:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongodb:27017/laWiki?authSource=admin

  wiki-service:
    build:
      context: ./services/wiki-service
      dockerfile: Dockerfile
    container_name: wiki-service
    ports:
      - "3004:3000"
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://admin:admin@mongodb:27017/laWiki?authSource=admin

volumes:
  mongo-data:
  mongo-config:
