name: CI tests

on:
  push:
  pull_request:

jobs:
  backend-test:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend   # Set the default working directory to backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'         # Specify your Node.js version or other runtime

      - name: Install backend dependencies
        run: npm install             # Adjust this command if you're using a different package manager

      - name: Run backend tests
        run: npm test
